/**
 * Facturación API
 * Api de Spring boot para modulo de facturación
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * modelo que representa a factura en la base de datos
 */
export interface Factura { 
    id?: number;
    clienteId?: number;
    numero?: string;
    detail?: string;
    monto?: number;
}